package sound;

public enum Sfx {
	SWORD, DENY, MAGIC, EAT, THROW, GAMEOVER, GAMESTART, SELECT,
	FIRE, POISON, DAMAGE, THORN, SHIELD, DODGE, VAMPIRIC, CLICK,
	SUMMONER, ANGER, HEAL, DEAD, STONERUN, GRASSRUN
}
