package sound;

public enum Sfx {
	SWORD, DENY, MAGIC, EAT, THROW, GAMEOVER, GAMESTART, SELECT, LEVELUP,
	FIRE, POISON, DAMAGE, THORN, SHIELD, DODGE, VAMPIRIC, CLICK, MAP,
	SUMMONER, ANGER, HEAL, DEAD, STONERUN, GRASSRUN, OUTSIDEOFBACKPACK, INSIDEOFBACKPACK, DRAG
}
